CREATE DATABASE fridgedb;

\c fridgedb;

CREATE TABLE IF NOT EXISTS fridges (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model character varying(255),
    prod character varying(255),
    country_prod character varying(255),
    cost numeric(10, 2),
    volume integer
);
