CREATE DATABASE fridgedb;

\c fridgedb;

CREATE TABLE IF NOT EXISTS fridges (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model character varying(255),
    prod character varying(255),
    country_prod character varying(255),
    cost numeric(10, 2),
    volume integer
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255),
    password character varying(255),
    user_role character varying(255)
);
